actor_fc1_units: 256
actor_fc2_units: 256
batch_size: 512
buffer_size: 1000000
clamp_value: 1
clip_grad: true
critic_fc2_units: 512
critic_fcs1_units: 512
gamma: 0.95
lr_actor: 0.001
lr_critic: 0.001
seed: 48
sigma: 0.1
tau: 0.02
update_every: 1
use_batchnorm: false
weight_decay: 0
